
CREATE PROC XEM_DU_AN
AS
BEGIN
SELECT* FROM DuAn
END
XEM_DU_AN

CREATE PROC THEM_DU_AN(
@TEN_DA NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
IF @MA_PB IN (SELECT maPB FROM PhongBan)
   INSERT INTO DuAn(tenDA, diaDiem,ngayBatDau,ngayKetThuc, maPB) VALUES (@TEN_DA,@DIA_DIEM,@NGAY_BD,@NGAY_KT,@MA_PB)
IF @MA_PB NOT IN (SELECT maPB FROM PhongBan)
   INSERT INTO PhongBan(maPB) VALUES(@MA_PB)
END
THEM_DU_AN 'g','fd','2017-6-7','2017-6-12',1

CREATE PROC SUA_DU_AN(
@MA_DA INT,
@TEN_DA NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
UPDATE DuAn SET tenDA=@TEN_DA, diaDiem=@DIA_DIEM, ngayBatDau=@NGAY_BD, ngayKetThuc=@NGAY_KT, maPB=@MA_PB WHERE maDA=@MA_DA
END

CREATE PROC XOA_DU_AN(
@MA_DA INT
)
AS
BEGIN
DELETE FROM DuAn WHERE maDA=@MA_DA
END

CREATE PROC XEM_THAM_GIA(
@MA_DA INT
)
AS
BEGIN
SELECT* FROM ThamGia WHERE maDA=@MA_DA
END
XEM_THAM_GIA 1

create proc GET_EMPL_NAME (@MA_NV int) as
begin
select TenNV from NhanVien
where maNV = @MA_NV
end

